### ISSUE TITLE
Colossus dependency in dm_halo_dist.py

### ISSUE THREAD

**Issue by evavagiakis** [deepskies/DeepSZSim#210]
https://github.com/deepskies/DeepSZSim/blob/main/deepszsim/dm_halo_dist.py

Does dm_halo_dist.py need to import colossus? If not can we delete that?

**Comment by samueldmcdermott** [comment]
looks to me like those imports could be deleted!

**Comment by evavagiakis** [comment]
Sounds good to me! You mentioned at one point doing some merges -- any upcoming that you can include this in, or are those all done and I can make a direct edit? @samueldmcdermott

**Comment by samueldmcdermott** [comment]
all good to make edits in `dev` or create a new branch off of `dev` for this and anything else you'd like!

**Comment by samueldmcdermott** [comment]
I actually did this recently and didn't update here, closing now
