### ISSUE TITLE
Update readme to include figures that show the physics and workflow

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepSZSim#226]
can use figures in joss paper.

and add a little bit of explanation of the figures

**Comment by samueldmcdermott** [comment]
How closely do we want the text of the paper to be reflected in the readme?

**Comment by bnord** [comment]
I think the readme should contain a summary of the physics and then should explain how to use the code. I suggest including images from the joss paper to help show how it works and what people can expect to get out of it.

**Comment by samueldmcdermott** [comment]
should be addressed in [98bba18](https://github.com/deepskies/DeepSZSim/commit/98bba1890ad2f43062733f010fa16661c26e3929)
