### ISSUE TITLE
update Config yaml files

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepSZSim#227]
1. Do we need the information at the top of this yaml file? https://github.com/deepskies/DeepSZSim/blob/joss/deepszsim/Settings/config.yaml
2. Could we make it clear which yaml file is for which task 
    3. e.g., change the filenames to reflect which one is an example
    4. change the filenames to make a bit more sense. why is one called config and the other is called inputdata?

**Comment by samueldmcdermott** [comment]
@samueldmcdermott will:
- [ ] delete the top lines in config.yaml
- [ ] change name of config.yaml to config_everything.yaml
- [ ] change name of inputdata.yaml to config_demo.yaml
